// @ts-check

/**
 * One sidebar per language.
 *
 * Docs autogenerate from their own folder, so opening a language shows only
 * that language's contents — the homepage is what switches between them.
 * Adding a language is two steps: create `syllabus/<lang>/`, then add a
 * `<lang>Sidebar` entry here.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  nodejsSidebar: [{type: 'autogenerated', dirName: 'nodejs'}],
  expressjsSidebar: [{type: 'autogenerated', dirName: 'expressjs'}],
};

export default sidebars;
