// @ts-check

/**
 * One sidebar per language.
 *
 * Docs autogenerate from their own folder, so opening a language shows only
 * that language's contents — the homepage is what switches between them.
 * Adding a language is two steps: create `syllabus/<lang>/`, then add a
 * `<lang>Sidebar` entry here.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  nodejsSidebar: [{type: 'autogenerated', dirName: 'nodejs'}],
  expressjsSidebar: [{type: 'autogenerated', dirName: 'expressjs'}],
  postgresqlSidebar: [{type: 'autogenerated', dirName: 'postgresql'}],
  mongodbSidebar: [{type: 'autogenerated', dirName: 'mongodb'}],
  redisSidebar: [{type: 'autogenerated', dirName: 'redis'}],
  typescriptSidebar: [{type: 'autogenerated', dirName: 'typescript'}],
  javascriptSidebar: [{type: 'autogenerated', dirName: 'javascript'}],
  cssSidebar: [{type: 'autogenerated', dirName: 'css'}],
  gitSidebar: [{type: 'autogenerated', dirName: 'git'}],
  dockerSidebar: [{type: 'autogenerated', dirName: 'docker'}],
  reactSidebar: [{type: 'autogenerated', dirName: 'react'}],
  nginxSidebar: [{type: 'autogenerated', dirName: 'nginx'}],
  storybookSidebar: [{type: 'autogenerated', dirName: 'storybook'}],
  viteSidebar: [{type: 'autogenerated', dirName: 'vite'}],
  webpackSidebar: [{type: 'autogenerated', dirName: 'webpack'}],
  babelSidebar: [{type: 'autogenerated', dirName: 'babel'}],
  eslintOxlintSidebar: [{type: 'autogenerated', dirName: 'eslint-oxlint'}],
  jestRtlSidebar: [{type: 'autogenerated', dirName: 'jest-rtl'}],
  playwrightSidebar: [{type: 'autogenerated', dirName: 'playwright'}],
  reduxToolkitSidebar: [{type: 'autogenerated', dirName: 'redux-toolkit'}],
  tanstackQuerySidebar: [{type: 'autogenerated', dirName: 'tanstack-query'}],
  framerMotionSidebar: [{type: 'autogenerated', dirName: 'framer-motion'}],
  webVitalsPerformanceSidebar: [{type: 'autogenerated', dirName: 'web-vitals-performance'}],
  frontendArchitectureSidebar: [{type: 'autogenerated', dirName: 'frontend-architecture'}],
  realworldSidebar: [{type: 'autogenerated', dirName: 'real-world'}],
};

export default sidebars;
