import React, {useMemo, useSyncExternalStore} from 'react';
import Category from '@theme-original/DocSidebarItem/Category';
import {
  subscribe,
  getSnapshot,
  getServerSnapshot,
} from '@site/src/components/StudyMode/store';
import {TIER_CODES} from '@site/src/data/tiers.mjs';
import '../studyMode.module.css';

/**
 * A sidebar category row, with how big it is and how far through it you are.
 *
 * Design finding 06: Java's phase 10 (Data access) holds 585 pages and phase 14
 * (Messaging) holds 1, and today they are two identical rows. Nothing on screen
 * says which one costs an afternoon. The number closes that.
 *
 * ── Two numbers, two sources, deliberately not the same denominator ──────────
 * The count on the right is the SIZE of the subtree, read straight out of the
 * build-time tally. The bar underneath is PROGRESS, computed from the doc ids in
 * the subtree.
 *
 * They cannot share a denominator, and that is why only one of them shows a
 * number. `tallyTiers` counts a category's own index page when it has a badge —
 * and a topic directory's README does (`scripts/tier-map.mjs`: it is a real
 * badged page and in the sidebar it is the category the chunks live under). But a
 * category sidebar item carries `href`, never `docId` — `docId` is on
 * `PropSidebarItemLink` only — so nothing can ever mark that README read. Printing
 * `11/12` for a topic that is fully read is a lie the reader would chase; a bar
 * that fills when every *link* in the subtree is read is not.
 *
 * ── Which size: total, or what survives the floor ────────────────────────────
 * What survives the floor. The count's job is to predict what opening the row
 * costs, and under Study Mode the row opens onto a filtered tree — "585" above a
 * category that expands to twelve rows is worse than no number at all. It stays
 * O(1): sum the tally's buckets at or above the floor. With Study Mode off the
 * floor is the widest tier, every bucket is included, and the number is the plain
 * total — which is the common case.
 *
 * ── 🔴 Where the numbers may NOT come from ───────────────────────────────────
 * Not from walking `item.items` on every render. This component re-renders on
 * every route change (`activePath`) and phase 10 has 585 descendants; at
 * expand-all that walk would run for every category on every navigation, which is
 * O(n · depth) over the whole tree. The size is O(1) from `customProps.tiers`.
 * The progress numerator genuinely needs the ids, so it is walked once and cached
 * on item identity — see {@link subtreeDocIds}.
 *
 * ── What is NOT re-implemented ───────────────────────────────────────────────
 * Everything the theme's Category owns: collapse state, auto-expand on the active
 * page, the caret button, the `autoCollapseCategories` behaviour, and the fallback
 * to a plain link when a category has no visible children. This wrapper adds
 * attributes to the anchor and hands the item straight back.
 */
export default function DocSidebarItemCategoryWrapper({item, ...props}) {
  const {floor, visited} = useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot);

  const docIds = useMemo(() => subtreeDocIds(item), [item]);

  const read = useMemo(() => {
    // The overwhelmingly common case on a first visit, and it skips the walk of
    // up to 585 ids that would otherwise return 0.
    if (visited.size === 0) return 0;
    let count = 0;
    for (const docId of docIds) {
      if (visited.has(docId)) count += 1;
    }
    return count;
  }, [docIds, visited]);

  const total = countAtOrAbove(item.customProps?.tiers, floor);

  /**
   * A category with no children is about to be rendered by the theme as a plain
   * link to its own index page (`DocSidebarItemCategoryEmpty`), or as nothing at
   * all if it has no index page. Both take `{...props}` with them, so these
   * attributes would land on a link row and pick up the category styling. It has
   * no size worth printing either — the tally would be its own single page.
   *
   * The theme decides this with `useVisibleSidebarItems`, which also drops
   * unlisted docs, so a category whose children are ALL unlisted slips past this
   * guard. That costs a stray count on one link row in a corpus with no unlisted
   * docs; running the filter a second time to close it does not pay for itself.
   *
   * `total === 0` is the other way in: a category the sidebar generator never
   * decorated has no tally at all. Those are hand-written sidebars rather than
   * autogenerated ones, and they get no number — which is the honest answer, and
   * a good deal better than printing "0" beside a category full of pages.
   */
  if (!item.items?.length || total === 0) {
    return <Category item={item} {...props} />;
  }

  // `docIds.length`, not `total`: the bar can only fill as far as the rows that
  // carry a doc id, which is every link in the subtree and none of the nested
  // category index pages. Floors below 1% still show, or a first read of a
  // 585-page phase would draw an invisible bar and look broken.
  const percent = read > 0 ? Math.max(2, Math.round((read / docIds.length) * 100)) : 0;

  return (
    <Category
      item={item}
      {...props}
      data-db-count={String(total)}
      {...(percent > 0 && {
        'data-db-progress': '',
        style: {'--db-progress': `${percent}%`},
      })}
      title={describe(total, read)}
    />
  );
}

/**
 * The bar and the count are shape and hue; this is the same information in words,
 * for a screen reader and for anyone who wants the exact figure. `title` rather
 * than `aria-label` for the reason spelled out in the Link wrapper: `aria-label`
 * would replace the row's accessible name with a page count.
 */
function describe(total, read) {
  const pages = `${total} ${total === 1 ? 'page' : 'pages'}`;
  return read > 0 ? `${pages} · ${read} read` : pages;
}

/**
 * How many pages in this subtree are at or above the floor.
 *
 * O(1) — the tally was computed once, at build time, by `decorateSidebarItems`.
 * `none` is always included: an untiered page is one nobody has tiered yet, and
 * the floor never hides those.
 */
function countAtOrAbove(tiers, floor) {
  if (!tiers) return 0;

  const limit = TIER_CODES.indexOf(floor);
  // An unrecognised floor must not silently zero the count; treat it as the
  // widest, which is what the store falls back to anyway.
  const last = limit >= 0 ? limit : TIER_CODES.length - 1;

  let count = tiers.none ?? 0;
  for (let i = 0; i <= last; i += 1) {
    count += tiers[TIER_CODES[i]] ?? 0;
  }
  return count;
}

/**
 * Every doc id under a category, cached on the item object itself.
 *
 * 🔴 The cost this avoids. The walk is O(subtree), and the subtrees are large:
 * 585 descendants under one Java phase, six levels deep, 6,797 pages across 29
 * sidebars. This component re-renders on every navigation, so an uncached walk
 * would repeat that for every category on screen, every time the reader turns a
 * page.
 *
 * A WeakMap keyed on the item object makes it once per category per tree. Item
 * identity is stable exactly as long as the tree is: `DocSidebarItems` memoises
 * its rewrite on `[items, floor, mode]`, so navigation does not touch it, and a
 * floor or collapse-all change produces new item objects and correctly earns a
 * fresh walk. WeakMap rather than Map because those old trees must be collectable
 * — a Map would pin every tree the reader has ever filtered into.
 *
 * The floor is not a parameter, and must not become one: by the time an item
 * reaches here the root has already pruned the tree, so what is left IS what
 * survives the current floor. Filtering again would be dead code that looks
 * load-bearing.
 */
const DOC_IDS = new WeakMap();

function subtreeDocIds(item) {
  const cached = DOC_IDS.get(item);
  if (cached) return cached;

  const ids = [];
  collect(item.items ?? [], ids);
  DOC_IDS.set(item, ids);
  return ids;
}

function collect(items, out) {
  for (const child of items) {
    if (child.type === 'category') {
      collect(child.items ?? [], out);
    } else if (child.docId) {
      out.push(child.docId);
    }
  }
}
