import re,html,sys
s=open(sys.argv[1],encoding='utf-8',errors='replace').read()
s=re.sub(r'(?is)<(script|style|head)[^>]*>.*?</\1>',' ',s)
s=re.sub(r'(?is)</(p|div|li|tr|h1|h2|h3|h4|pre|table|ul|ol|dt|dd)>','\n',s)
s=re.sub(r'(?is)<br[^>]*>','\n',s)
s=re.sub(r'(?is)</t[dh]>',' | ',s)
s=re.sub(r'(?s)<[^>]+>',' ',s)
s=html.unescape(s)
s=re.sub(r'[ \t\xa0]+',' ',s)
s=re.sub(r'\n\s*\n+','\n',s)
print(s)
