#!/usr/bin/env node
/**
 * Read every page's priority tier out of the corpus, keyed by Docusaurus doc id.
 *
 *   node scripts/tier-map.mjs          # print the distribution and exit
 *   node scripts/tier-map.mjs --json   # print the map itself
 *
 * `docusaurus.config.js` imports {@link buildTierMap} and uses it from
 * `sidebarItemsGenerator`, so every autogenerated sidebar link carries its tier
 * in `customProps` before it ever reaches the browser. Study Mode reads it there.
 *
 * ── Why this is not a committed JSON file ────────────────────────────────────
 * `src/data/page-counts.json` is committed because React components read it at
 * runtime. This map is different on both counts:
 *
 *   1. It is only ever needed on the Node side, during sidebar generation. What
 *      reaches the client is one letter per sidebar item, inside the sidebar
 *      payload the page already ships.
 *   2. It would be ~6,500 lines that change whenever anyone touches a badge, in
 *      a checkout several sessions write to at once. `src/data/progress.js` is
 *      already that hotspot ([[devbible-feedback-shared-file-staging]]); a
 *      second one is not worth a second of build time.
 *
 * Cost of doing it in-process instead: one pass over the corpus at config load,
 * memoised for the 29 sidebars. It reads the first 4 KB of each file and only
 * falls back to the whole file when no badge is found there, because the house
 * style puts the badge directly under the frontmatter.
 *
 * ── The counting rule ────────────────────────────────────────────────────────
 * 🔴 A page's tier is the FIRST `db-tier t-…` in it and nothing later
 * ([[devbible-feedback-count-by-first-tier-badge]]). Phase index pages and
 * syllabus pages list their topics in a table with a badge on every row, so the
 * second match onward belongs to some other page. Those index pages get NO tier
 * here at all:
 *
 *   docs/<track>/README.md            track overview          — excluded
 *   docs/<track>/syllabus/*.md        the topic inventory     — excluded
 *   docs/<track>/pages/README.md      the track's page index  — excluded
 *   docs/<track>/pages/<phase>/README.md   phase index        — excluded
 *   docs/<track>/pages/<phase>/<topic>/README.md  topic index — KEPT
 *
 * The last line is the exception that matters: a chunk directory's README
 * carries its own topic's tier, once, before its chunk table — so it is a real
 * badged page, and in the sidebar it is the category the chunks live under.
 */

import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

// One copy of the tier vocabulary, shared with the browser bundle — see the
// `.mjs` note in that file for why it is not a `.js`.
import {TIERS} from '../src/data/tiers.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const CODE_BY_SLUG = new Map(TIERS.map((tier) => [tier.slug, tier.code]));

/** The first badge in the file, e.g. `<span className="db-tier t-master">`. */
const BADGE = /db-tier\s+t-([a-z-]+)/;

/** Enough to clear the frontmatter, the badge and the `> Verified:` line. */
const HEAD_BYTES = 4096;

/**
 * The first tier badge in a file, as a tier code, or null.
 *
 * Reads the head of the file first. A page whose badge is further down than
 * that is unusual but legal — the fallback reads the whole file rather than
 * silently calling it untiered, because "untiered" is a visible state in the UI.
 */
function readTier(absPath) {
  let head = '';
  let fd;
  try {
    fd = fs.openSync(absPath, 'r');
    const buffer = Buffer.allocUnsafe(HEAD_BYTES);
    const bytes = fs.readSync(fd, buffer, 0, HEAD_BYTES, 0);
    head = buffer.toString('utf8', 0, bytes);
  } catch {
    return null;
  } finally {
    if (fd !== undefined) fs.closeSync(fd);
  }

  let match = BADGE.exec(head);
  if (!match && head.length === HEAD_BYTES) {
    try {
      match = BADGE.exec(fs.readFileSync(absPath, 'utf8'));
    } catch {
      return null;
    }
  }
  return match ? (CODE_BY_SLUG.get(match[1]) ?? null) : null;
}

/**
 * Does this doc get a tier at all?
 *
 * `relPath` is POSIX-separated and relative to `docs/`, e.g.
 * `java/pages/phase-4-lambdas-streams/02-method-references.md`.
 */
function isTieredPage(relPath) {
  const segments = relPath.split('/');

  // <track>/pages/... only. Syllabus, reviews and the track README are indexes.
  if (segments[1] !== 'pages') return false;

  if (segments[segments.length - 1] !== 'README.md') return true;

  // A README is a real page only from the topic level down: the track index
  // (pages/README.md, 3 segments) and a phase index (pages/<phase>/README.md,
  // 4) both hold tables of other pages' badges.
  return segments.length > 4;
}

/** `@site/docs/java/pages/x.md` → the absolute path it means. */
function resolveSource(source, siteDir) {
  return source.startsWith('@site/')
    ? path.join(siteDir, source.slice('@site/'.length))
    : path.resolve(siteDir, source);
}

let cached = null;

/**
 * `Map<docId, tierCode>` for the whole corpus.
 *
 * Pass the `docs` array Docusaurus hands to `sidebarItemsGenerator` and the map
 * is keyed off the ids and sources it already knows — no guessing at how a file
 * path becomes a doc id, which is the part that would quietly rot the day
 * someone sets `id:` in frontmatter. Called without it (the CLI), it walks
 * `docs/` and derives ids the same way the plugin does.
 *
 * Memoised: 29 autogenerated sidebars would otherwise each pay for a full pass.
 */
export function buildTierMap({siteDir = ROOT, docs = null} = {}) {
  if (cached) return cached;

  const map = new Map();

  if (docs) {
    for (const doc of docs) {
      if (!doc.source) continue;
      const abs = resolveSource(doc.source, siteDir);
      const rel = path.relative(path.join(siteDir, 'docs'), abs).split(path.sep).join('/');
      if (!isTieredPage(rel)) continue;
      const tier = readTier(abs);
      if (tier) map.set(doc.id, tier);
    }
  } else {
    walk(path.join(siteDir, 'docs'), path.join(siteDir, 'docs'), map);
  }

  cached = map;
  return map;
}

/** CLI-only: the plugin's own id rule is `<path under docs/>` minus `.md`. */
function walk(dir, docsRoot, map) {
  let entries;
  try {
    entries = fs.readdirSync(dir, {withFileTypes: true});
  } catch {
    return;
  }
  for (const entry of entries) {
    if (entry.name.startsWith('_')) continue;
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === 'reviews') continue;
      walk(abs, docsRoot, map);
      continue;
    }
    if (!entry.name.endsWith('.md')) continue;
    const rel = path.relative(docsRoot, abs).split(path.sep).join('/');
    if (!isTieredPage(rel)) continue;
    const tier = readTier(abs);
    if (tier) map.set(rel.replace(/\.md$/, ''), tier);
  }
}

/**
 * Attach `customProps.tier` to every link and category in a sidebar item tree.
 *
 * Categories get the tier of their own index page when they have one, plus a
 * `tiers` tally of everything beneath them — that tally is what lets the sidebar
 * decide whether a category survives the tier floor without walking its subtree
 * on every render, and what the progress ring divides into.
 *
 * Returns new objects; the generator's output is not mutated in place.
 */
export function decorateSidebarItems(items, tierMap) {
  return items.map((item) => decorateItem(item, tierMap));
}

function decorateItem(item, tierMap) {
  if (item.type === 'category') {
    const children = decorateSidebarItems(item.items ?? [], tierMap);
    const own = item.link?.type === 'doc' ? (tierMap.get(item.link.id) ?? null) : null;
    return {
      ...item,
      items: children,
      customProps: {...item.customProps, tier: own, tiers: tallyTiers(children, own)},
    };
  }

  if (item.type !== 'link' && item.type !== 'ref' && item.type !== 'doc') {
    return item;
  }

  // Autogenerated sidebars carry `docId` on every link item; `id` is what the
  // pre-resolution shapes use. Take whichever is present rather than assuming.
  const id = item.docId ?? item.id;
  const tier = id ? (tierMap.get(id) ?? null) : null;
  return {...item, customProps: {...item.customProps, tier}};
}

/**
 * `{m: 12, u: 8, k: 0, w: 0, none: 3}` for a subtree.
 *
 * `none` counts pages with no badge — 289 of them corpus-wide, plus every
 * syllabus page. Study Mode never hides those: an unbadged page is one nobody
 * has tiered yet, and a filter that swallows it makes it unreachable rather
 * than deferred.
 */
function tallyTiers(children, ownTier) {
  const tally = {m: 0, u: 0, k: 0, w: 0, none: 0};
  if (ownTier) tally[ownTier] += 1;

  for (const child of children) {
    if (child.type === 'category') {
      const nested = child.customProps?.tiers;
      if (!nested) continue;
      for (const key of Object.keys(tally)) tally[key] += nested[key] ?? 0;
    } else {
      const tier = child.customProps?.tier;
      tally[tier ?? 'none'] += 1;
    }
  }
  return tally;
}

// ─────────────────────────────────────────────────────────────── CLI ──────────
if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const started = Date.now();
  const map = buildTierMap();

  if (process.argv.includes('--json')) {
    console.log(JSON.stringify(Object.fromEntries(map), null, 2));
  } else {
    const perTier = new Map(TIERS.map((tier) => [tier.code, 0]));
    const perTrack = new Map();

    for (const [id, code] of map) {
      perTier.set(code, perTier.get(code) + 1);
      const track = id.split('/')[0];
      perTrack.set(track, (perTrack.get(track) ?? 0) + 1);
    }

    for (const tier of TIERS) {
      console.log(`${tier.label.padEnd(12)} ${String(perTier.get(tier.code)).padStart(5)}`);
    }
    console.log(`${'—'.repeat(18)}\n${'badged'.padEnd(12)} ${String(map.size).padStart(5)}`);
    console.log(
      `\n${[...perTrack].sort((a, b) => b[1] - a[1]).map(([t, n]) => `${t} ${n}`).join(' · ')}`,
    );
    console.log(`\n${Date.now() - started} ms`);
  }
}
